# Generated by Django 5.2.7 on 2025-11-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioIngrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(blank=True, max_length=50)),
                ('cantidad_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sabor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_elaboracion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('ingrediente', models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.inventarioingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='inventarioingrediente',
            name='proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.cliente')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.empleado')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='app_Paleteria.producto')),
            ],
        ),
    ]
