# Generated by Django 5.2.7 on 2025-11-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Paleteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioingrediente',
            old_name='proveedor',
            new_name='id_proveedor',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='ingrediente',
            new_name='id_ingrediente',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='empleado',
            new_name='id_empleado',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='id_producto',
        ),
    ]
